name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        BRANCH:
          - 9.0.x
          - 8.2.x
          - 8.1.x
          - 8.0.x
          - 1.7.8.x
        include:
          - BRANCH: 9.0.x
            node: 20
          - BRANCH: 8.2.x
            node: 16
          - BRANCH: 8.1.x
            node: 16
          - BRANCH: 8.0.x
            node: 14
          - BRANCH: 1.7.8.x
            node: 14

    env:
      PHP_VERSION: '7.4'
      NODE_VERSION: ${{ matrix.node }}
      RELEASE_DIR: '/tmp/ps-release'
      GH_BRANCH: ${{ matrix.BRANCH }}
      XML_FILE: ${{ matrix.BRANCH == 'develop' && 'nightly.xml' || format('nightly_{0}.xml', matrix.BRANCH)}}
      ZIP_FILE: ${{ matrix.BRANCH == 'develop' && 'nightly.zip' || format('nightly_{0}.zip', matrix.BRANCH)}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.GH_BRANCH }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Create Release directory
        run: mkdir -p ${{ env.RELEASE_DIR }}

      - name: Create build
        run: php tools/build/CreateRelease.php --destination-dir=${{ env.RELEASE_DIR }}

      - name: Rename build
        run: today=`date +%Y-%m-%d`; for i in *; do mv $i $today-$GH_BRANCH-$i; done
        working-directory: ${{ env.RELEASE_DIR }}

      - name: Create zip & xml for each branch
        run: |
          today=`date +%Y-%m-%d`
          cp $today-$GH_BRANCH*.zip ${{ env.ZIP_FILE }}
          cp $today-$GH_BRANCH*.xml ${{ env.XML_FILE }}
        working-directory: ${{ env.RELEASE_DIR }}
